383_Phase_1/Controllers/InventoryItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _383_Phase_1.Models;
using _383_Phase_1.DAL;
using System.Web.Security;

namespace _383_Phase_1.Controllers
{
    [Authorize]
    public class InventoryItemsController : Controller
    {
        private PhaseOneDbContext db = new PhaseOneDbContext();

        [AllowAnonymous]
        // GET: InventoryItems
        public ActionResult Index()
        {
                return View(db.InventoryItems.ToList());
        }

        [AllowAnonymous]
        // GET: InventoryItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = db.InventoryItems.Find(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }

            return View(inventoryItem);

        }

        // GET: InventoryItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InventoryItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Quantity")] InventoryItem inventoryItem)
        {
            if (ModelState.IsValid)
            {
                var username = User.Identity.Name;
                if(username != null)
                {
                    var uc = new UsersController();
                    User user = uc.UserFromName(username);
                    inventoryItem.CreatedByUserId = user.Id;
                    db.InventoryItems.Add(inventoryItem);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(inventoryItem);
        }

        // GET: InventoryItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = db.InventoryItems.Find(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // POST: InventoryItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CreatedByUserId,Name,Quantity")] InventoryItem inventoryItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventoryItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inventoryItem);
        }

        // GET: InventoryItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = db.InventoryItems.Find(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // POST: InventoryItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InventoryItem inventoryItem = db.InventoryItems.Find(id);
            db.InventoryItems.Remove(inventoryItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

383_Phase_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
    <script src="/SignalR/hubs"></script>
    <script src="~/Scripts/knockout-3.4.0.debug.js"></script>
    <script src="~/Scripts/InventoryUpdate.js"></script>

</head>
<body>
    <style>
        .navbar{
            background-color:#048545;
            border-bottom : 2px solid #048545;
        }
        .navbar-inverse .navbar-nav > li > a{
            color: #fff;
        }
    </style>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("G2P1 Inventory", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style="font-weight:bold;color:#fff !important;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Games List", "Index", "InventoryItems", new { area = "" }, null)</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Users", "Index", "Users", new { area = "" }, null)</li>
                    }
                </ul>

                <ul class="nav navbar-nav pull-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                             <li class="pull-right">@Html.ActionLink("Logout", "Logout", "Account", new { area = "" }, null)</li>

                            <li class="pull-right">
                                <a>Welcome, @Html.Raw(User.Identity.Name)</a>
                            </li>
                    }
                    else
                    {
                        <li class="pull-right">@Html.ActionLink("Login", "Login", "Account", new { area = "" }, null)</li>
                    }
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - G2P1 Inventory</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>